services:
  ubuntu: 
    container_name: ubuntu
    hostname: ubuntu
    image: psyoblade/data-engineer-ubuntu:22.04-slim
    restart: always
    tty: true
    volumes:
      - ./ubuntu/example:/example
  mysql:
    container_name: mysql
    hostname: mysql
    image: psyoblade/data-engineer-mysql:1.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - '3306:3306'
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - ./mysql/etc:/etc/mysql/conf.d
  trino-coordinator:
    container_name: trino-coordinator
    hostname: trino-coordinator
    image: trinodb/trino:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '8082:8080'        # 호스트 8082 → Trino 8080
    volumes:
      - ./trino/etc:/etc/trino:ro   # Trino 설정 마운트
    networks:
      - default

networks:
  default:
    name: data_engineer_intermediate_day1_network
