services:
  ubuntu:
    container_name: ubuntu
    hostname: ubuntu
    image: psyoblade/data-engineer-ubuntu:22.04-slim
    restart: always
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    cap_add:
      - NET_ADMIN
    volumes:
      - ./example:/example
  mysql:
    container_name: mysql
    hostname: mysql
    image: psyoblade/data-engineer-mysql:1.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
    ports:
      - '3306:3306'
    cap_add:
      - NET_ADMIN

networks:
  default:
    name: data_engineer_intermediate_day1_ubuntu_network
