version: "3"

services:
  ubuntu:
    container_name: ubuntu
    hostname: ubuntu
    image: psyoblade/data-engineer-ubuntu:20.04
    restart: always
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    cap_add:
      - NET_ADMIN
    volumes:
      - ./example:/example
  mysql:
    container_name: mysql
    hostname: mysql
    image: psyoblade/data-engineer-mysql:1.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: sqoop
      MYSQL_PASSWORD: sqoop
    ports:
      - '3306:3306'
    cap_add:
      - NET_ADMIN

networks:
  default:
    name: data_engineer_intermediate_day1_ubuntu_network
