FROM python:3.11-slim

ARG JUPYTER_TOKEN=lab
ARG SPARK_REMOTE=sc://connect-server:15002

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    JUPYTER_TOKEN=${JUPYTER_TOKEN} \
    SPARK_REMOTE=${SPARK_REMOTE}

# tini: safe PID1
RUN apt-get update && apt-get install -y --no-install-recommends tini \
 && rm -rf /var/lib/apt/lists/*

# w/o spark runtime
RUN pip install --no-cache-dir \
      jupyterlab==4.2.5 \
      pyspark-connect==4.0.1 \
      httpx==0.27.2 \
      pandas==2.2.2 \
      pyarrow==17.0.0

# non root
RUN useradd -m -u 1000 -s /bin/bash ubuntu
USER ubuntu

WORKDIR /work
EXPOSE 8888

CMD tini -g -- sh -lc 'jupyter lab \
--IdentityProvider.token="$JUPYTER_TOKEN" \
--ServerApp.ip=0.0.0.0 --ServerApp.port=8888 --ServerApp.open_browser=False \
--ServerApp.root_dir=/work'

